### ISSUE TITLE
Consertar o local dos pixels de detecção

### ISSUE THREAD

**Issue by rodrigo-xavier** [rodrigo-xavier/GuitarHero#22]
Os pixels estão meio tortos, verificar a posição correta para todas as cores.

**Comment by cesaraugc** [comment]
O principal problema está no verde. Provavelmente os pixels de rastro dele estão incorretos, já que não está detectando corretamente.

**Comment by cesaraugc** [comment]
Acredito que este não seja o problema e o local dos pixels estão bons.
