### ISSUE TITLE
Não apertar duas vezes

### ISSUE THREAD

**Issue by Alec-ryo** [rodrigo-xavier/GuitarHero#42]
Analisar o sistema pra não apertar duas vezes a mesma nota

**Comment by cesaraugc** [comment]
Isso ainda ocorre?

**Comment by rodrigo-xavier** [comment]
Infelizmente ainda ocorre, pois a solução que implementamos para resolver este problema não passava de uma imensa gambiarra. No entanto pretendemos resolver utilizando flags para as notas, ao invés de utilizar um tempo mínimo especulativo como era antes.
